# Generated by Django 3.2 on 2023-09-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('preco', models.PositiveIntegerField()),
                ('lucro', models.PositiveIntegerField()),
                ('imageUrl', models.CharField(max_length=300)),
            ],
        ),
    ]
